version: "3.9"

services:
  php73:
    build:
      context: ./docker/php73
    hostname: php73
    ports:
      - "9000:9000"
    volumes:
      - ./projects/:/var/www/html
      - ./docker/php73/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php73/php.ini:/usr/local/etc/php/php.ini
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    ports:
      - "80:80"
    volumes:
      - ./projects/:/var/www/html/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php73
  mysql:
    restart: always
    container_name: app-mysql
    command: --default-authentication-plugin=mysql_native_password
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    restart: always
    links:
      - mysql:db
    depends_on:
      - mysql